### ISSUE TITLE
Undefined array key "code" error in Typesense.php:170 when updating searchable model

### ISSUE THREAD

**Issue by gandesc** [typesense/laravel-scout-typesense-driver#16]
## Description

When updating a searchable attribute for a searchable model, the searchable() update throws an error.

This issue occurs on the typesense driver `5.0.1` but not on `5.0.0`.

The culprit seems to be in the `Typesense\LaravelTypesense\Typesense` class, in the `importDocuments` method, when the import method response structure does not match the looped check.

Is somehow the 5.0.1 version expected to work with a newer server version?

## Steps to reproduce

To reproduce, update any searchable attribute for a searchable model.

## Expected Behavior

Model updated/uploaded successfully to the typesense server, without errors.

## Actual Behavior

Model updated/uploaded **successfully** to the typesense server, WITH an error.

```
[2021-12-03 14:53:48] local.ERROR: Undefined array key "code" {"userId":2,"exception":"[object] (ErrorException(code: 0): Undefined array key \"code\" at /home/bravo/_work/_proj/rolcrispa/vendor/typesense/laravel-scout-typesense-driver/src/Typesense.php:170)
[stacktrace]
#0 /home/redacted/vendor/typesense/laravel-scout-typesense-driver/src/Typesense.php(170): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/redacted/vendor/typesense/laravel-scout-typesense-driver/src/Engines/TypesenseEngine.php(86): Typesense\\LaravelTypesense\\Typesense->importDocuments()
#2 /home/redacted/vendor/laravel/scout/src/Searchable.php(62): Typesense\\LaravelTypesense\\Engines\\TypesenseEngine->update()
#3 /home/redacted/vendor/laravel/scout/src/Searchable.php(41): LaravelEnso\\Products\\Models\\Product->queueMakeSearchable()
#4 /home/redacted/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(124): Illuminate\\Database\\Eloquent\\Collection->Laravel\\Scout\\{closure}()
#5 /home/redacted/vendor/laravel/scout/src/Searchable.php(169): Illuminate\\Support\\Collection->__call()
#6 /home/redacted/vendor/laravel/scout/src/ModelObserver.php(109): LaravelEnso\\Products\\Models\\Product->searchable()
#7 /home/redacted/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(528): Laravel\\Scout\\ModelObserver->saved()
#8 [internal function]: Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#9 /home/redacted/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(84): call_user_func()
#10 /home/redacted/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(529): Illuminate\\Database\\DatabaseTransactionsManager->addCallback()
#11 /home/redacted/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(424): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#12 /home/redacted/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#13 /home/redacted/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\\Events\\Dispatcher->dispatch()
#14 /home/redacted/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1035): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#15 /home/redacted/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1006): Illuminate\\Database\\Eloquent\\Model->finishSave()
#16 /home/redacted/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(885): Illuminate\\Database\\Eloquent\\Model->save()
#17 /home/redacted/vendor/laravel-enso/products/src/Http/Controllers/Update.php(14): Illuminate\\Database\\Eloquent\\Model->update()
#18 /home/redacted/vendor/laravel-enso/product-eav/src/Http/Controllers/Update.php(15): LaravelEnso\\Products\\Http\\Controllers\\Update->__invoke()
#19 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): LaravelEnso\\ProductEav\\Http\\Controllers\\Update->__invoke()
#20 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#21 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#22 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#23 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#24 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#25 /home/redacted/vendor/laravel-enso/localisation/src/Http/Middleware/SetLanguage.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): LaravelEnso\\Localisation\\Http\\Middleware\\SetLanguage->handle()
#27 /home/redacted/vendor/laravel-enso/permissions/src/Http/Middleware/VerifyRouteAccess.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): LaravelEnso\\Permissions\\Http\\Middleware\\VerifyRouteAccess->handle()2
#29 /home/redacted/vendor/laravel-enso/impersonate/src/Http/Middleware/Impersonate.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): LaravelEnso\\Impersonate\\Http\\Middleware\\Impersonate->handle()
#31 /home/redacted/vendor/laravel-enso/action-logger/src/Http/Middleware/ActionLogger.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): LaravelEnso\\ActionLogger\\Http\\Middleware\\ActionLogger->handle()
#33 /home/redacted/vendor/laravel-enso/core/src/Http/Middleware/VerifyActiveState.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): LaravelEnso\\Core\\Http\\Middleware\\VerifyActiveState->handle()
#35 /home/redacted/vendor/laravel-enso/control-panel-api/src/Http/Middleware/RequestMonitor.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): LaravelEnso\\ControlPanelApi\\Http\\Middleware\\RequestMonitor->handle()
#37 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#39 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#41 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#42 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#43 /home/redacted/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#45 /home/redacted/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#47 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#49 /home/redacted/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/redacted/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#51 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#52 /home/redacted/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#54 /home/redacted/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#56 /home/redacted/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#58 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/redacted/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#60 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#61 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#63 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#64 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#65 /home/redacted/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#66 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#67 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#68 /home/redacted/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestIpMiddleware.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Sentry\\Laravel\\Http\\SetRequestIpMiddleware->handle()
#70 /home/redacted/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Sentry\\Laravel\\Http\\SetRequestMiddleware->handle()
#72 /home/redacted/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#74 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#76 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#77 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#79 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#80 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#82 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#84 /home/redacted/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#86 /home/redacted/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#88 /home/redacted/vendor/laravel-enso/core/src/Http/Middleware/AuthorizationCookie.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#89 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): LaravelEnso\\Core\\Http\\Middleware\\AuthorizationCookie->handle()
#90 /home/redacted/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#91 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#92 /home/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#93 /home/redacted/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#94 /home/bravo/.config/composer/vendor/cpriego/valet-linux/server.php(232): require('...')
#95 {main}
"}
```

## Metadata

**Typsense Version**: 0.21.0 (locally hosted)

**OS**:  Linux Mint 19.3, Kernel Linux 5.4.0-90-generic x86_64

Other relevant versions:
`laravel/framework` `v8.74.0`
`laravel/scout` `v9.3.2`
`typesense/laravel-scout-typesense-driver` `v5.0.1`

**Comment by hi019** [comment]
Hey. A fix is in master, I'll release when #17 is merged
